[mypy]
python_version = 3.11
warn_unused_configs = True
warn_redundant_casts = True
warn_return_any = False
warn_unused_ignores = False
no_implicit_optional = True
strict_equality = True
disallow_incomplete_defs = False
disallow_untyped_defs = False
show_error_codes = True
pretty = True
ignore_missing_imports = True
exclude = ^(backend/tests|bff/tests|tests)/

# Temporarily relax type checks for backend and bff until annotations improve
[mypy-backend.*]
ignore_errors = True
[mypy-bff.*]
ignore_errors = True
[mypy-frontend.*]
ignore_errors = True
[mypy-backend.tests.*]
ignore_errors = True
[mypy-bff.tests.*]
ignore_errors = True

